# Account-Specific IAM Roles Configuration
# These roles are deployed to Specific accounts based on the Department
# Custom policies will be auto-discovered from the respective Role folder under policies/customer_managed_policies/{roleName}/ and attached to the role.
# Trust relationships will be auto-discovered from the respective Role folder under trust_relationships/{roleName}/ and attached to the role.

