# Standard IAM Roles Configuration
# These roles are deployed to respective accounts based on the Department in new and existing accounts.
# AWS Managed Policies will be auto-discovered from policies/aws_managed_policies/{roleName}/ folder.
# Customer Managed policies will be auto-discovered from policies/customer_managed_policies/{roleName}/ folder.
# Trust relationships will be auto-discovered from the respective Role folder under trust_relationships/{roleName}/ and attached to the role.


standard:
  Digital:
    - AE-AMI-AUDIT
    - AE-AWS-AUDITOR
    - AE-AWS-BI
    - AE-AWS-BIADMIN
    - AE-AWS-BROADOPS
    - AE-AWS-DATAVA
    - AE-AWS-DBA
    - AE-AWS-DBASS
    - AE-AWS-DEVELOPERS
    - AE-AWS-DEVELOPERS-ME
    - AE-AWS-DEVOPS
    - AE-AWS-DEVOPSADMIN
    - AE-AWS-ENG-ARCHIVE
    
  Technology:

    - AG-Test-StandardRole-1:
        - AdministratorAccess
        - AG-Test-StandardRole-1
    - AG-Test-StandardRole-2:
        - AdministratorAccess
        - AG-Test-StandardRole-1
        - AG-Test-StandardRole-2   

  Production Engineering:
    - AE-AWS-TECHLABADMIN
    - AE-AWS-TECHOPS
    - AE-AWS-VIEWADMIN
    - AE-Administrator
    - AE-COMP-AUDIT
    - AE-DBA
    - AE-Developer
    - AE-Engineering
    - AE-RI-INVENTORY
    - AE-Security
    - CROSS-ACC-ARMADA
  International:
    - AE-AWS-INTL-ADMIN
    - AE-AWS-INTL-DEVELOPERS
    - AE-AWS-INTL-DEVOPS
    - AE-AWS-INTL-ENG-ARCHIVE
    - AE-AWS-INTL-ENG-DEVELOPERS
    - AE-AWS-INTL-ENG-MEDIAOPS
    - AE-AWS-INTL-HACKATHON
    - AE-AWS-INTL-INFRENG
    - AE-AWS-INTL-L1TECHOPS
    - AE-AWS-INTL-MPXDEV
    - AE-AWS-INTL-NETWORK
    - AE-AWS-INTL-QA
    - AE-AWS-INTL-RESEARCH
    - AE-AWS-INTL-RO
    - AE-AWS-INTL-RW
    - AE-AWS-INTL-SEC
    - AE-AWS-INTL-TECHADMIN
    - AE-AWS-INTL-TECHLAB