# Standard IAM Roles Configuration
# These roles are deployed to respective accounts based on the Department in new and existing accounts.
# AWS Managed Policies will be auto-discovered from policies/aws_managed_policies/{roleName}/ folder.
# Customer Managed policies will be auto-discovered from policies/customer_managed_policies/{roleName}/ folder.
# Trust relationships will be auto-discovered from the respective Role folder under trust_relationships/{roleName}/ and attached to the role.


standard:
  Digital:
    - AE-AMI-AUDIT
    - AE-AWS-AUDITOR
    - AE-AWS-BI
    - AE-AWS-BIADMIN
    - AE-AWS-BROADOPS
    - AE-AWS-DATAVA
    - AE-AWS-DBA
    - AE-AWS-DBASS
    - AE-AWS-DEVELOPERS
    - AE-AWS-DEVELOPERS-ME
    - AE-AWS-DEVOPS
    - AE-AWS-DEVOPSADMIN
    - AE-AWS-ENG-ARCHIVE
    
  Technology:
    - AE-AWS-AUDITOR:
        - AE-AWS-AUDITOR-POL
    - AE-AWS-BI
    - AE-AWS-BIADMIN
    - AE-AWS-BROADOPS
    - AE-AWS-DATAVA:
        - AE-AWS-DATAVA-POL1
    - AE-AWS-DBASS
    - AE-AWS-DEVELOPERS:
        - AE-AWS_DEVELOPERS-POL1
    - AE-AWS-DEVELOPERS-ME
    - AE-AWS-DEVOPS:
        - AE-AWS-DEVOPS-NONPROD-POL1
        - AE-AWS-DEVOPS-NONPROD-POL2
        - AE-AWS-DEVOPS-NONPROD-POL3
        - AE-AWS-DEVOPS-PROD-POL1
        - AE-AWS-DEVOPS-PROD-POL2
    - AE-AWS-DEVOPSADMIN:
        - AE-AWS-DEVOPSADMIN-POL
    - AE-AWS-ENG-ARCHIVE
    - AE-AWS-ENG-DEVELOPERS
    - AE-AWS-ENG-MEDIAOPS
    - AE-AWS-INFRENG:
        - ReadOnlyAccess
        - AE-INFRENG-POL
        - AE-INFRENG-POL-2
    - AE-AWS-L1TECHOPS:
        - ReadOnlyAccess
        - AE-AWS-L1TECHOPS-POL
    - AE-AWS-MPXDEV
    - AE-AWS-NETWORK:
        - AE-NETOWRK-POL
    - AE-AWS-QA:
        - AE-AWS-QA-POL
    - AE-AWS-RESEARCH
    - AE-AWS-RO
    - AE-AWS-RW
    - AE-AWS-SEC:
        - SecurityAudit
        - AE-CF-Pol
        - AE-GaurdDuty-Pol
    - AE-AWS-TECHADMIN:
        - AdministratorAccess
        - AE-AWS-ADMIN-POL
    - AE-AWS-TECHLAB
    - AE-AWS-TECHLABADMIN
    - AE-AWS-TECHOPS:
        - ReadOnlyAccess
        - AE-AWS-TechOps-Pol
        - AE-AWS-L1TECHOPS-POL
    - AE-AWS-VIEWADMIN
    - AE-AMI-AUDIT:
        - AmazonEC2ReadOnlyAccess
        - AmazonRDSReadOnlyAccess
    - AE-AWS-IAM
    - AE-COMP-AUDIT:
        - ReadOnlyAccess
    - AE-Developer
    - AE-Engineering
    - AE-RI-INVENTORY:
        - AmazonRedshiftReadOnlyAccess
        - AmazonEC2ReadOnlyAccess
        - AmazonElastiCacheReadOnlyAccess
        - AmazonRDSReadOnlyAccess
    - AE-Security
    - ae_tag_volume_lambda_function:
        - ae_tag_volume_policy

  Production Engineering:
    - AE-AWS-TECHLABADMIN
    - AE-AWS-TECHOPS
    - AE-AWS-VIEWADMIN
    - AE-Administrator
    - AE-COMP-AUDIT
    - AE-DBA
    - AE-Developer
    - AE-Engineering
    - AE-RI-INVENTORY
    - AE-Security
    - CROSS-ACC-ARMADA
  International:
    - AE-AWS-INTL-ADMIN
    - AE-AWS-INTL-DEVELOPERS
    - AE-AWS-INTL-DEVOPS
    - AE-AWS-INTL-ENG-ARCHIVE
    - AE-AWS-INTL-ENG-DEVELOPERS
    - AE-AWS-INTL-ENG-MEDIAOPS
    - AE-AWS-INTL-HACKATHON
    - AE-AWS-INTL-INFRENG
    - AE-AWS-INTL-L1TECHOPS
    - AE-AWS-INTL-MPXDEV
    - AE-AWS-INTL-NETWORK
    - AE-AWS-INTL-QA
    - AE-AWS-INTL-RESEARCH
    - AE-AWS-INTL-RO
    - AE-AWS-INTL-RW
    - AE-AWS-INTL-SEC
    - AE-AWS-INTL-TECHADMIN
    - AE-AWS-INTL-TECHLAB